package com.fleetforyou.fleetforyou.Domain.Enums;

import java.util.*;

public enum Cars {
    Abarth_595("Abarth", "595"),
    Abarth_694("Abarth", "695"),
    Abarth_124("Abarth", "124 Spider"),
    ACCars_Cobra427("AC Cars", "Cobra 427"),
    ACCars_Ace("AC Cars","Ace"),
    Acura_MDX("Acura", "MDX"),
    Acura_RDX("Acura", "RDX"),
    Acura_TLX("Acura", "TLX"),
    Acura_NSX("Acura", "NSX"),
    AlfaRomeo_Giulia("Alfa Romeo", "Giulia"),
    AlfaRomeo_Stelvio("Alfa Romeo", "Stelvio"),
    Alpina_B3("Alpina", "B3"),
    Alpina_B4("Alpina", "B4"),
    Alpina_B7("Alpina", "B7"),
    Arrinera_Hussarya("Arrinera", "Hussarya"),
    AstonMartin_DB11("Aston Martin", "DB11"),
    AstonMartin_Vantage("Aston Martin", "Vantage"),
    AstonMartin_DBS_Superleggera("Aston Martin", "DBS Superleggera"),
    Audi_A3("Audi", "A3"),
    Audi_A4("Audi", "A4"),
    Audi_A6("Audi", "A6"),
    Audi_Q5("Audi", "Q5"),
    Audi_Q7("Audi", "Q7"),
    Audi_R8("Audi", "R8"),
    BAIC_X25("BAIC", "X25"),
    BAIC_X35("BAIC", "X35"),
    BAIC_X55("BAIC", "X55"),
    Bentley_ContinentalGT("Bentley", "Continental GT"),
    Bentley_Bentayga("Bentley", "Bentayga"),
    BMW_Series3("BMW", "Série 3"),
    BMW_Series5("BMW", "Série 5"),
    BMW_X3("BMW", "X3"),
    BMW_X5("BMW", "X5"),
    BMW_Series7("BMW", "Série 7"),
    BMW_M3("BMW", "M3"),
    BMW_M5("BMW", "M5"),
    Brabus_800("Brabus", "800"),
    Brabus_900("Brabus", "900"),
    Brabus_G_V12_900("Brabus", "G V12 900"),
    BrillianceAuto_V3("Brilliance Auto", "V3"),
    BrillianceAuto_V6("Brilliance Auto", "V6"),
    BrillianceAuto_V7("Brilliance Auto", "V7"),
    Bugatti_Chiron("Bugatti", "Chiron"),
    Bugatti_Veyron("Bugatti", "Veyron"),
    Buick_Encore("Buick", "Encore"),
    Buick_Enclave("Buick", "Enclave"),
    BYD_Tang("BYD", "Tang"),
    BYD_Song("BYD", "Song"),
    BYD_Qin("BYD", "Qin"),
    Cadillac_Escalade("Cadillac", "Escalade"),
    Cadillac_CTS("Cadillac", "CTS"),
    Cadillac_XT5("Cadillac", "XT5"),
    Chevrolet_Silverado("Chevrolet", "Silverado"),
    Chevrolet_Malibu("Chevrolet", "Malibu"),
    Chevrolet_Equinox("Chevrolet", "Equinox"),
    Chevrolet_Corvette("Chevrolet", "Corvette"),
    Chevrolet_Camaro("Chevrolet", "Camaro"),
    Chery_Tiggo8("Chery", "Tiggo 8"),
    Chery_Arrizo5("Chery", "Arrizo 5"),
    Chery_QQ("Chery", "QQ"),
    ChanganAutomobile_CS35("Changan Automobile", "CS35"),
    ChanganAutomobile_CS55("Changan Automobile", "CS55"),
    ChanganAutomobile_CS75("Changan Automobile", "CS75"),
    Citroen_C3("Citroën", "C3"),
    Citroen_C4("Citroën", "C4"),
    Citroen_Berlingo("Citroën", "Berlingo"),
    CodaAutomotive_CodaSedan("Coda Automotive", "Coda Sedan"),
    Cupra_Formentor("Cupra", "Formentor"),
    Cupra_Leon("Cupra", "Leon"),
    Cupra_Ateca("Cupra", "Ateca"),
    Dacia_Sandero("Dacia", "Sandero"),
    Dacia_Duster("Dacia", "Duster"),
    Daihatsu_Copen("Daihatsu", "Copen"),
    Daihatsu_Mira("Daihatsu", "Mira"),
    Datsun_Go("Datsun", "Go"),
    Datsun_GoPlus("Datsun", "Go+"),
    Datsun_Cross("Datsun", "Cross"),
    DeTomaso_P72("De Tomaso", "P72"),
    Dodge_Charger("Dodge", "Charger"),
    Dodge_Challenger("Dodge", "Challenger"),
    Dodge_Durango("Dodge", "Durango"),
    DSAutomobiles_DS3Crossback("DS Automobiles", "DS 3 Crossback"),
    DSAutomobiles_DS7Crossback("DS Automobiles", "DS 7 Crossback"),
    DSAutomobiles_DS9("DS Automobiles", "DS 9"),
    FaradayFuture_FF91("Faraday Future", "FF 91"),
    Ferrari_488GTB("Ferrari", "488 GTB"),
    Ferrari_F8Tributo("Ferrari", "F8 Tributo"),
    Ferrari_SF90Stradale("Ferrari", "SF90 Stradale"),
    Fiat_500("Fiat", "500"),
    Fiat_Panda("Fiat", "Panda"),
    Fiat_Tipo("Fiat", "Tipo"),
    Ford_Mustang("Ford", "Mustang"),
    Ford_F150("Ford", "F-150"),
    Ford_Focus("Ford", "Focus"),
    Ford_Escape("Ford", "Escape"),
    Ford_Explorer("Ford", "Explorer"),
    Genesis_G70("Genesis", "G70"),
    Genesis_G80("Genesis", "G80"),
    Genesis_GV80("Genesis", "GV80"),
    Geely_Coolray("Geely", "Coolray"),
    Geely_EmgrandX7("Geely", "Emgrand X7"),
    Geely_Binrui("Geely", "Binrui"),
    GMC_Sierra("GMC", "Sierra"),
    GMC_Yukon("GMC", "Yukon"),
    GreatWallMotors_HavalH6("Great Wall Motors", "Haval H6"),
    GreatWallMotors_HavalH9("Great Wall Motors", "Haval H9"),
    GreatWallMotors_WeyVV7("Great Wall Motors", "Wey VV7"),
    Holden_Commodore("Holden", "Commodore"),
    Holden_Colorado("Holden", "Colorado"),
    Holden_Acadia("Holden", "Acadia"),
    Honda_Civic("Honda", "Civic"),
    Honda_Accord("Honda", "Accord"),
    Honda_CRV("Honda", "CR-V"),
    Honda_Pilot("Honda", "Pilot"),
    Honda_Odyssey("Honda", "Odyssey"),
    HuanghaiAuto_N3("Huanghai Auto", "N3"),
    HuanghaiAuto_N5("Huanghai Auto", "N5"),
    HuanghaiAuto_N1("Huanghai Auto", "N1"),
    Hummer_H1("Hummer", "H1"),
    Hummer_H2("Hummer", "H2"),
    Hummer_H3("Hummer", "H3"),
    Hyundai_Sonata("Hyundai", "Sonata"),
    Hyundai_Elantra("Hyundai", "Elantra"),
    Hyundai_Tucson("Hyundai", "Tucson"),
    Hyundai_SantaFe("Hyundai", "Santa Fe"),
    Hyundai_Kona("Hyundai", "Kona"),
    Infiniti_Q50("Infiniti", "Q50"),
    Infiniti_QX60("Infiniti", "QX60"),
    Infiniti_QX80("Infiniti", "QX80"),
    Isuzu_DMax("Isuzu", "D-Max"),
    Isuzu_MUX("Isuzu", "MU-X"),
    IVECO_Daily("IVECO", "Daily"),
    IVECO_Stralis("IVECO", "Stralis"),
    IVECO_Trakker("IVECO", "Trakker"),
    JACMotors_S3("JAC Motors", "S3"),
    JACMotors_S4("JAC Motors", "S4"),
    JACMotors_S5("JAC Motors", "S5"),
    Jaguar_FPACE("Jaguar", "F-Pace"),
    Jaguar_XF("Jaguar", "XF"),
    Jaguar_XJ("Jaguar", "XJ"),
    Jeep_Wrangler("Jeep", "Wrangler"),
    Jeep_GrandCherokee("Jeep", "Grand Cherokee"),
    Jeep_Cherokee("Jeep", "Cherokee"),
    Jeep_Renegade("Jeep", "Renegade"),
    KarmaAutomotive_Revero("Karma Automotive", "Revero"),
    KarmaAutomotive_ReveroGT("Karma Automotive", "Revero GT"),
    Kia_Optima("Kia", "Optima"),
    Kia_Sportage("Kia", "Sportage"),
    Kia_Sorento("Kia", "Sorento"),
    Kia_Telluride("Kia", "Telluride"),
    Koenigsegg_Agera("Koenigsegg", "Agera"),
    Koenigsegg_Jesko("Koenigsegg", "Jesko"),
    Lada_Vesta("Lada", "Vesta"),
    Lada_Granta("Lada", "Granta"),
    Lada_Niva("Lada", "Niva"),
    Lamborghini_Huracan("Lamborghini", "Huracán"),
    Lamborghini_Aventador("Lamborghini", "Aventador"),
    Lamborghini_Urus("Lamborghini", "Urus"),
    Lancia_Ypsilon("Lancia", "Ypsilon"),
    Lancia_Thema("Lancia", "Thema"),
    LandRover_RangeRover("Land Rover", "Range Rover"),
    LandRover_Discovery("Land Rover", "Discovery"),
    LandRover_Defender("Land Rover", "Defender"),
    Lexus_ES("Lexus", "ES"),
    Lexus_RX("Lexus", "RX"),
    Lexus_NX("Lexus", "NX"),
    Lexus_LS("Lexus", "LS"),
    Lincoln_Navigator("Lincoln", "Navigator"),
    Lincoln_Continental("Lincoln", "Continental"),
    Lincoln_Aviator("Lincoln", "Aviator"),
    Lotus_Elise("Lotus", "Elise"),
    Lotus_Evora("Lotus", "Evora"),
    Maserati_Ghibli("Maserati", "Ghibli"),
    Maserati_Levante("Maserati", "Levante"),
    Maserati_Quattroporte("Maserati", "Quattroporte"),
    Mazda_Mazda3("Mazda", "Mazda3"),
    Mazda_Mazda6("Mazda", "Mazda6"),
    Mazda_CX5("Mazda", "CX-5"),
    Mazda_MX5Miata("Mazda", "MX-5 Miata"),
    McLaren_720S("McLaren", "720S"),
    McLaren_570S("McLaren", "570S"),
    McLaren_GT("McLaren", "GT"),
    MercedesBenz_ClasseC("Mercedes-Benz", "Classe C"),
    MercedesBenz_ClasseE("Mercedes-Benz", "Classe E"),
    MercedesBenz_GLE("Mercedes-Benz", "GLE"),
    MercedesBenz_GLC("Mercedes-Benz", "GLC"),
    MercedesBenz_ClasseS("Mercedes-Benz", "Classe S"),
    MercedesBenz_AMGGT("Mercedes-Benz", "AMG GT"),
    MINI_Cooper("MINI", "Cooper"),
    MINI_Countryman("MINI", "Countryman"),
    Mitsubishi_Outlander("Mitsubishi", "Outlander"),
    Mitsubishi_EclipseCross("Mitsubishi", "Eclipse Cross"),
    Mitsubishi_Pajero("Mitsubishi", "Pajero"),
    MorganMotorCompany_PlusFour("Morgan Motor Company", "Plus Four"),
    MorganMotorCompany_PlusSix("Morgan Motor Company", "Plus Six"),
    MorganMotorCompany_3Wheeler("Morgan Motor Company", "3 Wheeler"),
    NIO_ES8("NIO", "ES8"),
    NIO_ES6("NIO", "ES6"),
    NIO_EC6("NIO", "EC6"),
    Nissan_Altima("Nissan", "Altima"),
    Nissan_Rogue("Nissan", "Rogue"),
    Nissan_GTR("Nissan", "GT-R"),
    Nissan_Pathfinder("Nissan", "Pathfinder"),
    NobleAutomotive_M600("Noble Automotive", "M600"),
    NobleAutomotive_M500("Noble Automotive", "M500"),
    NobleAutomotive_M12("Noble Automotive", "M12"),
    Pagani_Huayra("Pagani", "Huayra"),
    Pagani_Zonda("Pagani", "Zonda"),
    Peugeot_208("Peugeot", "208"),
    Peugeot_3008("Peugeot", "3008"),
    Peugeot_5008("Peugeot", "5008"),
    Polestar_Polestar2("Polestar", "Polestar 2"),
    Porsche_911("Porsche", "911"),
    Porsche_Cayenne("Porsche", "Cayenne"),
    Porsche_Panamera("Porsche", "Panamera"),
    Porsche_Macan("Porsche", "Macan"),
    Proton_X70("Proton", "X70"),
    Proton_Saga("Proton", "Saga"),
    Proton_Iriz("Proton", "Iriz"),
    Qoros_3CitySUV("Qoros", "3 City SUV"),
    Qoros_5SUV("Qoros", "5 SUV"),
    Ram_1500("Ram", "1500"),
    Ram_2500("Ram", "2500"),
    Ram_3500("Ram", "3500"),
    Renault_Clio("Renault", "Clio"),
    Renault_Megane("Renault", "Megane"),
    Renault_Captur("Renault", "Captur"),
    RimacAutomobili_CTwo("Rimac Automobili", "C_Two"),
    Rivian_R1T("Rivian", "R1T"),
    Rivian_R1S("Rivian", "R1S"),
    Roewe_RX5("Roewe", "RX5"),
    Roewe_i5("Roewe", "i5"),
    Roewe_MarvelX("Roewe", "Marvel X"),
    RollsRoyce_Phantom("Rolls-Royce", "Phantom"),
    RollsRoyce_Cullinan("Rolls-Royce", "Cullinan"),
    RollsRoyce_Ghost("Rolls-Royce", "Ghost"),
    Saab_93("Saab", "9-3"),
    Saab_95("Saab", "9-5"),
    Scania_Sseries("Scania", "S-series"),
    Scania_Rseries("Scania", "R-series"),
    Scion_xB("Scion", "xB"),
    Scion_tC("Scion", "tC"),
    Scion_FRS("Scion", "FR-S"),
    SEAT_Leon("SEAT", "Leon"),
    SEAT_Ibiza("SEAT", "Ibiza"),
    SEAT_Arona("SEAT", "Arona"),
    Shelby_Cobra427("Shelby", "Cobra 427"),
    Shelby_GT500SuperSnake("Shelby", "GT500 Super Snake"),
    Škoda_Octavia("Škoda", "Octavia"),
    Škoda_Superb("Škoda", "Superb"),
    Škoda_Kodiaq("Škoda", "Kodiaq"),
    Smart_Fortwo("Smart", "Fortwo"),
    SsangYong_Rexton("SsangYong", "Rexton"),
    SsangYong_Tivoli("SsangYong", "Tivoli"),
    SsangYong_Korando("SsangYong", "Korando"),
    SpykerCars_C8Preliator("Spyker Cars", "C8 Preliator"),
    SpykerCars_C8Aileron("Spyker Cars", "C8 Aileron"),
    Subaru_Outback("Subaru", "Outback"),
    Subaru_Forester("Subaru", "Forester"),
    Subaru_Impreza("Subaru", "Impreza"),
    Suzuki_Swift("Suzuki", "Swift"),
    Suzuki_Vitara("Suzuki", "Vitara"),
    TataMotors_Tiago("Tata Motors", "Tiago"),
    TataMotors_Nexon("Tata Motors", "Nexon"),
    TataMotors_Harrier("Tata Motors", "Harrier"),
    Tatra_Phoenix("Tatra", "Phoenix"),
    Tatra_Jamal("Tatra", "Jamal"),
    Tatra_Terrno("Tatra", "Terrno"),
    Tesla_ModelS("Tesla", "Model S"),
    Tesla_Model3("Tesla", "Model 3"),
    Tesla_ModelX("Tesla", "Model X"),
    Tesla_ModelY("Tesla", "Model Y"),
    Toyota_Corolla("Toyota", "Corolla"),
    Toyota_Camry("Toyota", "Camry"),
    Toyota_RAV4("Toyota", "RAV4"),
    Toyota_Highlander("Toyota", "Highlander"),
    Toyota_Tacoma("Toyota", "Tacoma"),
    Tofaş_Kartal("Tofaş", "Kartal"),
    Tofaş_Sahin("Tofaş", "Sahin"),
    Tofaş_Dogan("Tofaş", "Dogan"),
    Troller_T4("Troller", "T4"),
    TVR_Griffith("TVR", "Griffith"),
    TVR_Tuscan("TVR", "Tuscan"),
    UAZ_Hunter("UAZ", "Hunter"),
    UAZ_Patriot("UAZ", "Patriot"),
    UAZ_Bukhanka("UAZ", "Bukhanka"),
    Vauxhall_Corsa("Vauxhall", "Corsa"),
    Vauxhall_Astra("Vauxhall", "Astra"),
    VectorMotors_W8("Vector Motors", "W8"),
    VectorMotors_M12("Vector Motors", "M12"),
    VenturiAutomobiles_Fetish("Venturi Automobiles", "Fetish"),
    VenturiAutomobiles_Astrolab("Venturi Automobiles", "Astrolab"),
    Venturi_Astrolab("Venturi", "Astrolab"),
    Venturi_400GT("Venturi", "400 GT"),
    Volkswagen_Golf("Volkswagen", "Golf"),
    Volkswagen_Jetta("Volkswagen", "Jetta"),
    Volkswagen_Passat("Volkswagen", "Passat"),
    Volkswagen_Tiguan("Volkswagen", "Tiguan"),
    Volkswagen_Atlas("Volkswagen", "Atlas"),
    Volvo_XC60("Volvo", "XC60"),
    Volvo_XC90("Volvo", "XC90"),
    Volvo_S60("Volvo", "S60"),
    Volvo_V60("Volvo", "V60"),
    WMotors_LykanHyperSport("W Motors", "Lykan HyperSport"),
    WMotors_FenyrSuperSport("W Motors", "Fenyr SuperSport"),
    Wiesmann_MF5("Wiesmann", "MF5"),
    Wiesmann_MF4("Wiesmann", "MF4"),
    Wuling_HongGuang("Wuling", "Hong Guang"),
    YemaAuto_T70("Yema Auto", "T70"),
    YemaAuto_T80("Yema Auto", "T80"),
    YemaAuto_T90("Yema Auto", "T90"),
    ZenvoAutomotive_TSR_S("Zenvo Automotive", "TSR-S"),
    ZenvoAutomotive_TS1GT("Zenvo Automotive", "TS1 GT");

    private final String brand;
    private final String model;

    Cars(String brand, String model) {
        this.brand = brand;
        this.model = model;
    }

    @Override
    public String toString() {
        return model;
    }

    public static Cars[] getSpecificModels(String brandInput) {
        return Arrays.stream(Cars.values())
                .filter(car -> car.brand.equals(brandInput))
                .toArray(Cars[]::new);
    }

    public static List<String> iterateByBrands() {
        Set<String> brands = new HashSet<>();
        for (Cars car : Cars.values()) {
            brands.add(car.brand);
        }

        List<String> brandNames = new ArrayList<>(brands);
        Collections.sort(brandNames);
        return brandNames;
    }
}